spring:
  application:
    name: secure

error:
  whitelabel:
    enabled: false

server:
  port: 8080
  servlet:
    context-path: /secure

management:
  endpoints:
    web:
      exposure:
        include: info, health
